"""Emit requirements-lock.txt pinning the EXACT installed versions of
the core dependencies.

Round-7 review: results_summary.json records source hashes and the git
commit, but the same commit on a different NumPy/SciPy can still change
numerics subtly, and requirements.txt is deliberately loose (floors
only, friendly to casual installs). This lockfile is the reproduction
counterpart: run it in the environment that produced the canonical
results, commit the output, and a third party can `pip install -r
requirements-lock.txt` to match. The manifest's `environment` block
records the same versions on every generation.

Usage:
    python scripts/write_lockfile.py
"""
from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# mirrors requirements.txt (tifffile/imagecodecs stay optional there and
# here — only needed to rebuild the population-grid asset)
CORE = ["numpy", "scipy", "pandas", "obspy", "seisbench", "torch",
        "matplotlib", "pillow", "huggingface_hub"]


def main() -> None:
    lines = ["# generated by scripts/write_lockfile.py — exact versions",
             "# used for the canonical results (see the `environment`",
             "# block in outputs/results_summary.json)"]
    missing = []
    for pkg in CORE:
        try:
            lines.append(f"{pkg}=={version(pkg)}")
        except PackageNotFoundError:
            missing.append(pkg)
    out = ROOT / "requirements-lock.txt"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[lock] wrote {out} ({len(lines) - 3} pins)")
    if missing:
        print(f"[lock] WARNING: not installed here, not pinned: "
              f"{missing}")


if __name__ == "__main__":
    main()
